force-app/main/default/objects/GuestArticleVote__c/GuestArticleVote__c.object-meta.xml
<CustomObject>
    <label>Guest Article Vote</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guest Article Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GuestArticleVote__c/fields/GuestUserId__c.field-meta.xml
<CustomField>
    <fullName>GuestUserId__c</fullName>
    <label>Guest User Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GuestArticleVote__c/fields/IsUpvoted__c.field-meta.xml
<CustomField>
    <fullName>IsUpvoted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upvoted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GuestArticleVote__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Guest Article Votes</relationshipLabel>
    <relationshipName>GuestArticleVotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GuestArticleVoteController.cls
public class GuestArticleVoteController {
    @AuraEnabled
    public static Boolean existsVoteResult(String articleVersionId, String guestUserId){
        Integer voteCount = [
            SELECT COUNT()
            FROM GuestArticleVote__c
            WHERE Knowledge__c = :articleVersionId AND GuestUserId__c = :guestUserId
        ];
        return (voteCount > 0);
    }

    @AuraEnabled
    public static void vote(String articleVersionId, String guestUserId, Boolean isUpvoted){
        insert new GuestArticleVote__c(
            Knowledge__c  = articleVersionId,
            GuestUserId__c = guestUserId,
            IsUpvoted__c = isUpvoted
        );
    }
}